### ISSUE TITLE
Json Recipes causing TE server hang.

### ISSUE THREAD

**Issue by Slaymeister** [anti344/JsonRecipes#1]
I seem to have misdirected this issue twice, as I did not find the erroring API in your package.  This may actually be your error.

Please refer to the following two issues for details:
https://github.com/CoFH/ThermalExpansion/issues/91
https://github.com/aidancbrady/Mekanism/issues/1724

Thanks!

**Comment by ghost** [comment]
Wow, stupid error. Does JsonRecipes work with BuildCraft at all?
Should be fixed in next version.

**Comment by ghost** [comment]
Yup, stupid mistake, fixed by ec39447

**Comment by ghost** [comment]
And it can't cause hangs since it handles the exception and just prints it to the console, so it's not JsonRecipes issue.

**Comment by Slaymeister** [comment]
Thank you.  I'm on a business trip, ATM, which creates logistic challenges for me in creating new builds (I'm working from an iPad and my dev machine is isolated from the RDP gateway).  If you are going to release a new build, I can remote into my minecraft host and load it into my staging server to evaluate the impact of the update.  Otherwise, I'll be able to provide feedback once I am home and able to create the new build.
